# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86160b649c8480afe38e75456f45d6bd5f66ad29f9e802f20f18f51f008a7e5ebb725d76a165f585fc9e2b003d9de6cb319094de5077d7b7bf8b40ea0a0840e7

test:
  secret_key_base: b35006ddf15fdeafe70e3e676f612b00c46948e2069574986780263d58b7d42b34f0ca772a591dcd284495ca7fb40af9884fdb31f61af5f5541f5de96ec23a1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: dff9f7bffecd593c28fe46b952e9f7b3400f200e3129d2d5c92dc34ceb164cf75758a4b11a1f586e45436c25ce611e602df09781bd98585647838c6ca5752a04
